### ISSUE TITLE
pagination 错位

### ISSUE THREAD

**Issue by Glimis** [iuap-design/iuap-design#13]
按照官网描述,写一遍,位置是不正确的

官网例子依赖

``` css
.book .book-body .page-wrapper .page-inner section.normal * {
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
   font-size: inherit;//错位解决- -
}
```

问题是 .book 是什么鬼
